<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows10.0.22000.0</TargetFramework>
		<RootNamespace>Kaeo.LlmProxy.Modules</RootNamespace>
		<AssemblyName>Kaeo LLM Proxy Modules</AssemblyName>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

</Project>
